name: monolog

services:
  api:
    container_name: monolog-api
    # image: ghcr.io/mo-no-log/api:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - postgresql
      - valkey

  postgresql:
    container_name: monolog-postgresql
    image: postgres:alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      TZ: Asia/Seoul
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data

  valkey:
    container_name: monolog-valkey
    image: valkey/valkey:alpine
    restart: unless-stopped
    sysctls:
      - vm.overcommit_memory=1
    environment:
      TZ: Asia/Seoul
